### ISSUE TITLE
Estudar sobre fila de mensagem

### ISSUE THREAD

**Issue by fpcardoso** [Smart-AniMon/docs#10]
- [x] Mosquitto
- [ ] RabbitMQ

**Comment by camillabarreto** [comment]
### MQTT

O protocolo MQTT é uma tecnologia de mensagens baseada em pub-sub leve desenvolvida para dispositivos IOT. É usado para comunicação com dispositivos remotos (que têm certas restrições) onde a largura de banda da rede é cara. O Facebook usa MQTT em seus aplicativos móveis.

- Não suporta roteamento de mensagens complexas.
- É eficiente em termos de cabeamento e os esforços de implementação em um cliente são menores.
- Ele suporta apenas a técnica de mensagens pub-sub. Não suporta filas de mensagens. (?)
- Em termos de segurança do usuário, permite senhas curtas e nomes de usuário que não fornecem segurança suficiente no mundo moderno. Em caso de qualquer alteração de política ou falha de segurança, seria necessária uma nova versão do protocolo.
- Seu único namespace de mensagem é um tópico e todas as mensagens irão para ele.

Links interessantes:
- https://developer.ibm.com/br/technologies/iot/articles/iot-mqtt-why-good-for-iot/
- https://mqtt.org/mqtt-specification/
- https://www.gta.ufrj.br/ensino/eel878/redes1-2019-1/vf/mqtt/

### Mosquitto (MQTT em C)
- https://mosquitto.org/
- https://mosquitto.org/api/files/mosquitto-h.html

### PAHO (MQTT em Python)
- https://www.eclipse.org/paho/index.php?page=clients/python/docs/index.php
- https://pypi.org/project/paho-mqtt/

**Comment by camillabarreto** [comment]
### RabbitMQ

Projetado como um protocolo de mensagens de propósito geral que pode ser usado para middleware orientado a mensagens e para transferência de dados ponto a ponto. Foi adotado por muitas grandes empresas / organizações como JP Morgan, NASA (para Nebula Cloud Computing) e Google. Na verdade, ele também encontra uso no Projeto Aadhar da Índia, que é o maior banco de dados biométrico do mundo.

- Suporta um poderoso roteamento de mensagens. É útil quando precisamos executar o mesmo trabalho em um servidor específico, grupo de servidores ou todos os servidores. O aplicativo envia uma mensagem e o Exchange a encaminha.
- Não é eficiente na fiação e requer mais esforço para implementação em um cliente. Para publicar mensagens em um nó, a primeira etapa é estabelecer um link, em seguida, habilitar o fluxo sobre esse link e, finalmente, enviar as mensagens.
- Ele oferece suporte a técnicas de mensagens de ponto a ponto e pub-sub.
- Ele implementa mecanismos SASL, permitindo que os usuários escolham a segurança que desejam (por exemplo, Kerberos v5) sem alterar o protocolo. Ele também oferece suporte a servidores de segurança proxy, permitindo que as organizações usem firewalls, gatekeepers aninhados, etc.
- Ele pode ter vários namespaces de mensagens e cada um deles oferece suporte a diferentes maneiras de localizar mensagens.

Links interessantes:

- https://medium.com/dev-cave/rabbit-mq-parte-i-c15e5f89d94#:~:text=em%20determinados%20cen%C3%A1rios.-,RabbitMQ,AMQP%20%E2%80%94%20Advanced%20Message%20Queueing%20Protocol.
- https://www.rabbitmq.com/documentation.html
