### ISSUE TITLE
Modelar formato das mensagens MQTT

### ISSUE THREAD

**Issue by camillabarreto** [Smart-AniMon/docs#16]

**Comment by fpcardoso** [comment]
Formato das mensagens enviadas do Módulo para o Servidor através do Broker MQTT.

{
"id":"Identificador do Modulo",
"image":"imagem convertida em bytes",
"temperatura":"float com valor da temperatura em ºC",
"umidade":"float com valor da umidade relativa em %",
"localização": {
                 "latitude":"String",
                 "longitude":"String"
               },
"data_captura": "String contendo data e hora da captura"
}
