### ISSUE TITLE
Estudar funcionamento do banco de dados NoSQL - MongoDB

### ISSUE THREAD

**Issue by camillabarreto** [Smart-AniMon/docs#17]

**Comment by fpcardoso** [comment]
Fiz um estudo sobre o funcionamento do banco de dados NoSQL, mais especificamente sobre o MongoDB.
Vi alguns exemplos de utilização do MongoDB com Python e notei que a biblioteca [pymongo](https://pymongo.readthedocs.io/en/stable/) é bastante utilizada.
Vou utilizar o pymongo no desenvolvimento da interface de conexão com o banco.
