### ISSUE TITLE
Revisar especificação - Incluir Fonte de alimentação para os módulos

### ISSUE THREAD

**Issue by fpcardoso** [Smart-AniMon/docs#3]

**Comment by camillabarreto** [comment]
- [x] Determinar o consumo de energia do módulo
- [x] Pesquisar por bateria com especificações que cubram o consumo de energia exigido
- [x] Pesquisar por modelo de placa fotovoltaica com especificações que cubram o consumo de energia exigido

**Comment by camillabarreto** [comment]
- **Determinar o consumo de energia do módulo**
Raspberry Pi 4 Model B (Wireless LAN) é alimentada com 5V e 3A através de uma interface USB.
`5V * 3A = 15W`

**Comment by camillabarreto** [comment]
- **Pesquisar por bateria com especificações que cubram o consumo de energia exigido**
A bateria deve armazenar no mínimo energia suficiente para alimentar o módulo por 12 horas diárias (período noturno).
`12h * 15W = 180Wh   =>   12h * 3000mA = 36000mAh`
Portanto, a bateria deve fornecer pelo menos 36000mAh.

**Comment by camillabarreto** [comment]
- **Pesquisar por modelo de placa fotovoltaica com especificações que cubram o consumo de energia exigido**
A placa fotovoltaica deve produzir num período de 12 horas diárias (período com iluminação solar) energia suficiente para carregar a bateria completamente e alimentar o módulo.
`15W + 15W = 30W`
